apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: analyze-technology
  namespace: default
spec:
  params:
  - name: SOURCE_PATH
    type: string
  results:
  - name: technology
  workspaces:
  - name: shared-data

  steps:
    - image: ubuntu # contains bash
      workingDir: $(workspaces.shared-data.path)/$(params.SOURCE_PATH)
      name: analyze
      script: |
        #!/usr/bin/env bash
        echo ">>> Analyze"
        ls
        echo ">>> Source Code:"
        ls
        if [[ -f "pom.xml" ]]
        then
          echo -n maven | tee $(results.technology.path)
          echo -e "\nThis is a Maven project!"
          cat $(results.technology.path)
        fi
        if [[ -f "build.gradle" ]]
        then
          echo -n gradle | tee $(results.technology.path)
          echo -e "\nThis is a Gradle project!"
          cat $(results.technology.path)
        fi
        if [[ -f "go.mod" ]]
        then
          echo -n golang | tee $(results.technology.path)
          echo -e "\nThis is a Golang project!"
          cat $(results.technology.path)
        fi
        if compgen -G "*.sln" > /dev/null || compgen -G "*/*.sln" > /dev/null
        then
          echo -n dotnet | tee $(results.technology.path)
          echo -e "\nThis is a .NetCore project!"
          cat $(results.technology.path)
        fi
        exit 0
