apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-unit-tests
  namespace: default
spec:
  params:
    - name: SOURCE_PATH
      type: string
  workspaces:
    - name: shared-data
  results:
    - name: pass
  steps:
    - image: docker.io/golang:latest@sha256:8ea012ba16112273afc171ff75ce517fe4edeb3849f6714554aa4e71fe54e4c1
      workingDir: $(workspaces.shared-data.path)/$(params.SOURCE_PATH)
      onError: stopAndFail
      name: run-tests
      script: |
        #!/usr/bin/env bash
        echo ">>> Unit-Tests"
        go test ./...
        if [[ $? -ne 0 ]] 
        then
          echo -e "\n\n[RESULT] ----------------------------------------------------------------------"
          echo -n "Passed all Unit-Tests: "
          echo -n false | tee $(results.pass.path)
          echo -e "\nExporting Unit-Test result into $(workspaces.shared-data.path)/unit-tests.result"
          echo "failed" > $(workspaces.shared-data.path)/unit-tests.result
          exit 1
        else
          echo -e "\n\n[RESULT] ----------------------------------------------------------------------"
          echo -n "Passed all Unit-Tests: "
          echo -n true | tee $(results.pass.path)
          echo -e "\nExporting Unit-Test result into $(workspaces.shared-data.path)/unit-tests.result"
          echo "passed" > $(workspaces.shared-data.path)/unit-tests.result
          exit 0
        fi
        exit 2
#      volumeMounts:
#        - name: my-volume
#          mountPath: /var/my-volume
#  volumes:
#    - name: my-volume
#      emptyDir: {}