apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-unit-tests
  namespace: default
spec:
  params:
    - name: SOURCE_PATH
      type: string
  workspaces:
    - name: shared-data
  results:
    - name: pass
  steps:
    - image: docker.io/maven:latest@sha256:d9035c93956cda1f067a6fe5d120c6c3575830dd651802e72c8e9376b78563b9
      workingDir: $(workspaces.shared-data.path)/$(params.SOURCE_PATH)
      onError: stopAndFail
      name: run-tests
      script: |
        #!/usr/bin/env bash
        echo ">>> Unit-Tests"
        mvn clean test
        if [[ $? -ne 0 ]] 
        then
          echo -e "\n\n[RESULT] ----------------------------------------------------------------------"
          echo -n "Passed all Unit-Tests: "
          echo -n false | tee $(results.pass.path)
          echo -e "\nExporting Unit-Test result into $(workspaces.shared-data.path)/unit-tests.result"
          echo "failed" > $(workspaces.shared-data.path)/unit-tests.result
          exit 1
        else
          echo -e "\n\n[RESULT] ----------------------------------------------------------------------"
          echo -n "Passed all Unit-Tests: "
          echo -n true | tee $(results.pass.path)
          echo -e "\nExporting Unit-Test result into $(workspaces.shared-data.path)/unit-tests.result"
          echo "passed" > $(workspaces.shared-data.path)/unit-tests.result
          exit 0
        fi
        exit 2